/** Central status -> Ant Design tag color mapping so badges look consistent everywhere. */
export const statusColor: Record<string, string> = {
  // generic
  Active: 'green',
  Inactive: 'default',
  Pending: 'gold',
  Completed: 'green',
  Cancelled: 'default',
  Draft: 'default',
  Archived: 'default',
  Published: 'blue',
  Expired: 'red',
  Failed: 'red',
  Success: 'green',
  Warning: 'gold',
  Failure: 'red',
  // patient
  Deceased: 'default',
  Low: 'green',
  Medium: 'gold',
  High: 'red',
  // appointments
  Scheduled: 'blue',
  Confirmed: 'cyan',
  'Checked In': 'geekblue',
  'In Progress': 'purple',
  'No Show': 'red',
  Rescheduled: 'orange',
  Routine: 'default',
  Urgent: 'orange',
  Emergency: 'red',
  STAT: 'red',
  // clinical
  Discontinued: 'red',
  'On Hold': 'gold',
  Chronic: 'purple',
  Resolved: 'green',
  Mild: 'green',
  Moderate: 'gold',
  Severe: 'orange',
  'Life-threatening': 'red',
  Signed: 'green',
  Amended: 'orange',
  Final: 'green',
  'Pending Review': 'gold',
  'Pending Sign-off': 'gold',
  Sent: 'blue',
  Filled: 'green',
  Ordered: 'blue',
  Collected: 'cyan',
  Resulted: 'green',
  Performed: 'cyan',
  Reported: 'green',
  Accepted: 'cyan',
  Declined: 'red',
  Due: 'gold',
  Overdue: 'red',
  // tasks
  Open: 'blue',
  Normal: 'default',
  // providers / users
  'On Leave': 'gold',
  Locked: 'red',
  'Pending Invite': 'gold',
  Valid: 'green',
  'Expiring Soon': 'orange',
  'Pending Verification': 'gold',
  Approved: 'green',
  Rejected: 'red',
  Swapped: 'orange',
  // rooms/resources
  Available: 'green',
  Occupied: 'blue',
  Maintenance: 'orange',
  Cleaning: 'gold',
  'In Use': 'blue',
  Retired: 'default',
};

export const priorityColor = statusColor;
