/**
 * Urdu / Roman-Urdu lexicon used by the transcript translator.
 *
 * Two token-level tables:
 *   - SCRIPT: Urdu-script tokens (after character normalisation) -> canonical Roman token
 *   - ROMAN:  Roman-Urdu spelling variants                       -> canonical Roman token
 *
 * "Canonical" tokens are the spellings the phrase/structure rules in translator.ts
 * are written against. English loanwords spelled in Urdu script ("پیج", "میڈیکیشن")
 * map straight to their English form so the rest of the pipeline never sees Urdu script.
 */

// ---------------------------------------------------------------- numbers
const ROMAN_NUMBERS: Array<[number, string[]]> = [
  [1, ['ek', 'aik', 'ik', 'eik']],
  [2, ['do']],
  [3, ['teen', 'tin', 'tean']],
  [4, ['char', 'chaar', 'chr']],
  [5, ['panch', 'paanch', 'pnch', 'panj']],
  [6, ['che', 'chay', 'chhe', 'chhay', 'chey', 'chhay', 'chh']],
  [7, ['saat', 'sat']],
  [8, ['aath', 'ath', 'aat']],
  [9, ['nau', 'naw', 'nou']],
  [10, ['das', 'dus', 'dass']],
  [11, ['gyara', 'gyarah', 'giyara', 'giyarah', 'gyaarah', 'gyarha']],
  [12, ['bara', 'barah', 'baara', 'baarah']],
  [13, ['tera', 'terah', 'taira', 'tairah']],
  [14, ['chauda', 'chaudah', 'choda', 'chodah', 'chowda', 'chaudha']],
  [15, ['pandra', 'pandrah', 'pandhra', 'pandhrah']],
  [16, ['sola', 'solah', 'soolah']],
  [17, ['satra', 'satrah', 'sattra', 'sattrah']],
  [18, ['athara', 'atharah', 'atthara', 'attharah']],
  [19, ['unnis', 'unees', 'unniss', 'unis', 'unees']],
  [20, ['bees', 'bis', 'beess']],
  [21, ['ikkis', 'ikees', 'ikis', 'akkis', 'ekees', 'ikees']],
  [22, ['bais', 'baees', 'baes', 'baais', 'baiss']],
  [23, ['teis', 'taees', 'tais']],
  [24, ['chaubis', 'chobees', 'chobis', 'chaubees', 'chowbees']],
  [25, ['pachees', 'pachis', 'pachchees', 'pachees']],
  [26, ['chhabbis', 'chabees', 'chabbis', 'chhabees', 'chabis']],
  [27, ['sattais', 'satais', 'sattaees', 'sataees']],
  [28, ['athais', 'athaees', 'atthais', 'atthaees', 'athaes']],
  [29, ['untis', 'untees', 'unattis', 'untiss']],
  [30, ['tees', 'tis', 'teess', 'tiss']],
  [31, ['ikattis', 'iktees', 'ikatees', 'aktees', 'ekatees']],
  [32, ['battis', 'batees', 'batis', 'battees']],
  [33, ['taintis', 'tentees', 'taintees', 'tentis']],
  [34, ['chauntis', 'chontees', 'chauntees', 'chontis']],
  [35, ['paintis', 'pentees', 'paintees', 'pentis']],
  [36, ['chhattis', 'chatees', 'chhatees', 'chattis']],
  [37, ['saintis', 'sentees', 'saintees', 'sentis']],
  [38, ['artis', 'artees', 'aartis', 'aartees']],
  [39, ['untalis', 'untalees', 'unchalis', 'untaalis']],
  [40, ['chalis', 'chalees', 'chaalis', 'chaalees']],
  [41, ['iktalis', 'iktalees', 'ektalis', 'ekhtalis']],
  [42, ['bayalis', 'bayalees', 'bealis', 'biyalis']],
  [43, ['taintalis', 'tentalis', 'taintalees', 'tentalees']],
  [44, ['chawalis', 'chawalees', 'chowalis', 'chawaalis']],
  [45, ['paintalis', 'pentalis', 'paintalees', 'pentalees']],
  [46, ['chheyalis', 'chiyalis', 'chhiyalees', 'chiyalees']],
  [47, ['saintalis', 'sentalis', 'saintalees', 'sentalees']],
  [48, ['artalis', 'artalees', 'aartalis', 'adtalis']],
  [49, ['unchas', 'unchaas', 'unanchas', 'unchass']],
  [50, ['pachas', 'pachaas', 'pchas']],
  [51, ['ikyawan', 'ikyaawan', 'ekyawan', 'ikyavan']],
  [52, ['bawan', 'baawan', 'bavan']],
  [53, ['tirpan', 'tirpun', 'tarpan']],
  [54, ['chawan', 'chowan', 'chawwan']],
  [55, ['pachpan', 'pachpun']],
  [56, ['chhappan', 'chappan', 'chhapan', 'chapan']],
  [57, ['sattawan', 'satawan', 'sattavan']],
  [58, ['atthawan', 'athawan', 'atthaavan']],
  [59, ['unsath', 'unsatth', 'unsaath']],
  [60, ['sath', 'saath', 'saathh', 'satth']],
  [61, ['iksath', 'iksatth', 'eksath']],
  [62, ['basath', 'basatth', 'baasath']],
  [63, ['tirsath', 'tirsatth', 'tersath']],
  [64, ['chausath', 'chonsath', 'chausatth']],
  [65, ['painsath', 'pensath', 'painsatth']],
  [66, ['chheyasath', 'chiyasath', 'chhiyasath']],
  [67, ['sarsath', 'sarsatth', 'sadsath']],
  [68, ['arsath', 'arsatth', 'adsath']],
  [69, ['unhattar', 'unhatar', 'unhattur']],
  [70, ['sattar', 'satar', 'sattur']],
  [71, ['ikhattar', 'ikhatar', 'ekhattar']],
  [72, ['bahattar', 'bahatar', 'bahattur']],
  [73, ['tihattar', 'tihatar', 'tehattar']],
  [74, ['chauhattar', 'chohattar', 'chauhatar']],
  [75, ['pachhattar', 'pachattar', 'pachhatar']],
  [76, ['chhihattar', 'chihattar', 'chhehattar']],
  [77, ['satattar', 'satatar', 'sattattar']],
  [78, ['athattar', 'athatar', 'atthattar']],
  [79, ['unasi', 'unaasi', 'unassi']],
  [80, ['assi', 'asi', 'assee']],
  [81, ['ikyasi', 'ikyaasi', 'ekyasi']],
  [82, ['bayasi', 'bayaasi', 'biyasi']],
  [83, ['tirasi', 'tiraasi', 'terasi']],
  [84, ['chaurasi', 'chorasi', 'chauraasi']],
  [85, ['pachasi', 'pachaasi', 'pichasi']],
  [86, ['chheyasi', 'chiyasi', 'chhiyasi']],
  [87, ['satasi', 'sataasi', 'sattasi']],
  [88, ['athasi', 'athaasi', 'atthasi']],
  [89, ['nawasi', 'nawaasi', 'navasi']],
  [90, ['nawwe', 'nabbe', 'nawe', 'nabe', 'navve']],
  [100, ['sau', 'so', 'sao']],
];

const SCRIPT_NUMBERS: Array<[number, string[]]> = [
  [1, ['ایک']], [2, ['دو']], [3, ['تین']], [4, ['چار']], [5, ['پانچ', 'پانج']], [6, ['چھ', 'چھے']], [7, ['سات']], [8, ['آٹھ', 'اٹھ']], [9, ['نو']], [10, ['دس']],
  [11, ['گیارہ', 'گیاره']], [12, ['بارہ']], [13, ['تیرہ']], [14, ['چودہ']], [15, ['پندرہ']], [16, ['سولہ']], [17, ['سترہ']], [18, ['اٹھارہ']], [19, ['انیس']], [20, ['بیس']],
  [21, ['اکیس']], [22, ['بائیس']], [23, ['تئیس']], [24, ['چوبیس']], [25, ['پچیس']], [26, ['چھبیس']], [27, ['ستائیس']], [28, ['اٹھائیس']], [29, ['انتیس']], [30, ['تیس']],
  [31, ['اکتیس']], [32, ['بتیس']], [33, ['تینتیس']], [34, ['چونتیس']], [35, ['پینتیس']], [36, ['چھتیس']], [37, ['سینتیس']], [38, ['اڑتیس']], [39, ['انتالیس']], [40, ['چالیس']],
  [41, ['اکتالیس']], [42, ['بیالیس']], [43, ['تینتالیس']], [44, ['چوالیس']], [45, ['پینتالیس']], [46, ['چھیالیس']], [47, ['سینتالیس']], [48, ['اڑتالیس']], [49, ['انچاس']], [50, ['پچاس']],
  [51, ['اکاون']], [52, ['باون']], [53, ['ترپن']], [54, ['چون']], [55, ['پچپن']], [56, ['چھپن']], [57, ['ستاون']], [58, ['اٹھاون']], [59, ['انسٹھ']], [60, ['ساٹھ']],
  [61, ['اکسٹھ']], [62, ['باسٹھ']], [63, ['تریسٹھ']], [64, ['چونسٹھ']], [65, ['پینسٹھ']], [66, ['چھیاسٹھ']], [67, ['سڑسٹھ']], [68, ['اڑسٹھ']], [69, ['انہتر']], [70, ['ستر']],
  [71, ['اکہتر']], [72, ['بہتر']], [73, ['تہتر']], [74, ['چوہتر']], [75, ['پچہتر']], [76, ['چھہتر']], [77, ['ستتر']], [78, ['اٹھہتر']], [79, ['اناسی']], [80, ['اسی']],
  [81, ['اکیاسی']], [82, ['بیاسی']], [83, ['تراسی']], [84, ['چوراسی']], [85, ['پچاسی']], [86, ['چھیاسی']], [87, ['ستاسی']], [88, ['اٹھاسی']], [89, ['نواسی']], [90, ['نوے']], [100, ['سو']],
];

// ---------------------------------------------------------------- roman variants -> canonical
// Each entry: canonical token followed by the spellings that map to it.
const ROMAN_VARIANTS: Array<[string, string[]]> = [
  // verbs (imperative forms are collapsed to one canonical token)
  ['jao', ['jao', 'jaao', 'jayen', 'jaen', 'jaein', 'jaiye', 'jaye', 'jaey', 'jaaen', 'jaayen', 'ja']],
  ['jana', ['jana', 'jaana', 'jaanaa']],
  ['chalo', ['chalo', 'chalein', 'chalen', 'chaliye', 'chaliyay', 'chal', 'chalay']],
  ['kholo', ['kholo', 'kholen', 'kholein', 'kholiye', 'khol', 'kholna', 'kholay', 'khool', 'kholdo', 'khulo']],
  ['dikhao', ['dikhao', 'dikhaen', 'dikhayen', 'dikhaiye', 'dikha', 'dikhana', 'dikhaye', 'dikhaao', 'dikhado', 'dikhaein']],
  ['karo', ['karo', 'kro', 'karen', 'karein', 'kariye', 'kijiye', 'kijye', 'kren', 'kr', 'kardo', 'krdo', 'kardein', 'karden', 'kariyay', 'karain', 'kerdo', 'kero', 'keren']],
  ['daalo', ['daalo', 'dalo', 'daal', 'dal', 'daalen', 'dalen', 'daalein', 'daaldo', 'daldo', 'dalein', 'daliye']],
  ['likho', ['likho', 'likhen', 'likhein', 'likh', 'likhiye', 'likhdo', 'likhein']],
  ['banao', ['banao', 'banaen', 'banayen', 'banaiye', 'bana', 'banana', 'banado', 'banaein', 'bnao', 'bnado']],
  ['dhoondo', ['dhoondo', 'dhundo', 'dhoondho', 'dhundho', 'dhoondein', 'dhoond', 'dhund', 'dhoondhen', 'dhundein']],
  ['rakho', ['rakho', 'rakhen', 'rakhein', 'rakh', 'rakhdo', 'rakhiye', 'rakhein']],
  ['hatao', ['hatao', 'hataen', 'hatayen', 'hata', 'hatado', 'mitao', 'mita', 'mitado', 'hataein', 'nikalo', 'nikal']],
  ['bhejo', ['bhejo', 'bhejen', 'bhej', 'bhejdo', 'bhejein', 'bhaijo']],
  ['roko', ['roko', 'ruko', 'ruk', 'rok', 'rukjao', 'rokdo']],
  ['band', ['band', 'bnd', 'bandh']],
  ['chupao', ['chupao', 'chhupao', 'chhipao', 'chipao', 'chupado']],
  ['chuno', ['chuno', 'chunein', 'chun', 'chunlo', 'chunen']],
  ['bharo', ['bharo', 'bhar', 'bhardo', 'bharen', 'bharein']],
  ['lagao', ['lagao', 'laga', 'lagado', 'lagaen', 'lagayen', 'lagaein']],
  ['chahiye', ['chahiye', 'chahiyay', 'chaiye', 'chahye', 'chahye', 'chaheye', 'chahiay', 'chaheay', 'chahie', 'chahta', 'chahti', 'chahte', 'chahtay', 'chata', 'chati', 'chahtaa']],
  ['hoon', ['hoon', 'hun', 'hu', 'hoo', 'hon']],
  ['hai', ['hai', 'hy', 'hain', 'hein', 'hen', 'hai', 'hae', 'hy']],
  ['saaf', ['saaf', 'saf']],
  ['khali', ['khali', 'khaali']],
  ['mehfooz', ['mehfooz', 'mahfooz', 'mehfuz', 'mahfuz']],
  // postpositions / particles
  ['par', ['par', 'pe', 'per', 'pr', 'pay', 'pey']],
  ['ko', ['ko', 'koo']],
  ['ke', ['ke', 'k', 'kay', 'kae', 'kai', 'kei']],
  ['ka', ['ka', 'kaa']],
  ['ki', ['ki', 'kee']],
  ['se', ['se', 'say', 'sey', 'sy']],
  ['mein', ['mein', 'me', 'mai', 'main', 'mn', 'may', 'mei', 'mien', 'men']],
  ['tak', ['tak', 'tk', 'tuk']],
  ['liye', ['liye', 'liay', 'liyay', 'lie', 'lye', 'liey', 'liya', 'liyea', 'liyye', 'lea', 'liyai', 'lyay', 'ly']],
  ['saath', ['saath', 'sath', 'sat', 'saat']], // context-resolved: "ke saath" = with; "saat" = 7 handled before this via numbers
  ['baad', ['baad', 'bad', 'bd', 'baat']],
  ['pehle', ['pehle', 'pehlay', 'phle', 'pahle', 'pehlle', 'pahlay', 'pehley']],
  ['wala', ['wala', 'wali', 'wale', 'walay', 'waale', 'waali', 'waala']],
  ['mujhe', ['mujhe', 'mujhay', 'muje', 'mjhe', 'mujay', 'mujhey', 'mujhko', 'mujh']],
  ['zara', ['zara', 'zra', 'please', 'plz', 'pls', 'meherbani', 'mehrbani']],
  ['naya', ['naya', 'nayi', 'naye', 'nai', 'nae', 'nayaa', 'nya', 'nyi']],
  ['aur', ['aur', 'or', 'aor', 'awr', 'aurr', 'ur']],
  ['phir', ['phir', 'fir', 'pher', 'fer', 'phr']],
  ['uske', ['uske', 'iske', 'usky', 'isky', 'uskay', 'iskay']],
  ['ab', ['ab', 'abhi', 'abi']],
  ['bhi', ['bhi', 'bi']],
  ['hi', ['hi']],
  ['ye', ['ye', 'yeh', 'yah', 'yea', 'is', 'isko', 'ise', 'esko', 'iss', 'yehi']],
  ['us', ['us', 'usko', 'use', 'uss']],
  // nouns
  ['dawai', ['dawai', 'dawa', 'dava', 'dawaai', 'dwai', 'dawayi', 'dawaiyan', 'dawaiyaan', 'dawaian', 'dawaien', 'dawaain', 'dawaiya', 'dwa', 'dawae', 'dawaeen']],
  ['mareez', ['mareez', 'mariz', 'marez', 'mareeza', 'mareezon', 'mareezo', 'mareezan']],
  ['page', ['page', 'safha', 'safa', 'sfa', 'sfha', 'pej', 'paij', 'safhay', 'safhe']],
  ['number', ['number', 'nambar', 'numbar', 'nmbr', 'nmbar', 'no.', 'num']],
  ['dosage', ['dosage', 'khuraak', 'khurak', 'khoraak', 'khorak', 'dose', 'khuraq']],
  ['din', ['din', 'dino', 'dinon', 'dinu', 'dinn', 'roz', 'dins']],
  ['hafta', ['hafta', 'hafte', 'hafton', 'haftay', 'haftey', 'hafto']],
  ['mahina', ['mahina', 'mahine', 'mahino', 'mahinay', 'maheena', 'maheenay', 'mahiney', 'maheene', 'mahinon']],
  ['saal', ['saal', 'sal', 'baras', 'saalon', 'saalo']],
  ['ghanta', ['ghanta', 'ghante', 'ghanton', 'ghantay', 'ghantey', 'ghanto', 'ghnta']],
  ['baje', ['baje', 'bajay', 'bje', 'bajey', 'bajy', 'bajaay', 'bajae', 'bajee']],
  ['subah', ['subah', 'subha', 'subh', 'subhe', 'sawere', 'saveray', 'subahh']],
  ['shaam', ['shaam', 'sham', 'shyam', 'shaamm', 'shamm']],
  ['dopahar', ['dopahar', 'dopehar', 'dupehar', 'dupahar', 'dopahr', 'dopeher']],
  ['raat', ['raat', 'rat', 'raatt', 'raath']],
  ['kal', ['kal', 'kl', 'kall']],
  ['aaj', ['aaj', 'aj', 'aajj']],
  ['parso', ['parso', 'parson', 'parsoon', 'parsu']],
  ['agle', ['agle', 'aglay', 'agla', 'agli', 'agley', 'aglee']],
  ['bar', ['bar', 'baar', 'dafa', 'dafaa', 'martaba', 'martabah', 'dafah', 'baari', 'martabaa']],
  ['waqt', ['waqt', 'waqat', 'wqt', 'waqth']],
  ['tablet', ['tablet', 'goli', 'goliyan', 'goliyaan', 'goliya', 'golian', 'tablets', 'tabletein']],
  ['capsule', ['capsule', 'kapsool', 'capsul', 'kapsol', 'capsules']],
  ['syrup', ['syrup', 'sharbat', 'sirup', 'shurbat']],
  ['injection', ['injection', 'teeka', 'tika', 'sui', 'sooi', 'injectn', 'teekay']],
  ['khana', ['khana', 'khanay', 'khane', 'khaane', 'khaana', 'khaney', 'khany']],
  ['sone', ['sone', 'sonay', 'soney', 'sote', 'sotay', 'sotey']],
  ['zaroorat', ['zaroorat', 'zarurat', 'zarorat', 'zaroorath', 'zarurath', 'zarorath', 'zroorat']],
  ['bukhar', ['bukhar', 'bukhaar', 'bokhar', 'bukharr']],
  ['dard', ['dard', 'drd', 'dardd']],
  ['sar', ['sar', 'sir', 'sr']],
  ['khansi', ['khansi', 'khaansi', 'khaasi', 'khasi', 'khansee']],
  ['zukam', ['zukam', 'zukaam', 'nazla', 'nazlah', 'zokam']],
  ['gala', ['gala', 'galay', 'gale', 'galey', 'gla']],
  ['kharab', ['kharab', 'kharaab', 'khrab']],
  ['pait', ['pait', 'pet', 'paet', 'peyt', 'paith']],
  ['seena', ['seena', 'seene', 'seenay', 'sina', 'sine', 'chhati', 'chati', 'seeney']],
  ['sugar', ['sugar', 'sheeni', 'shugar', 'shuger', 'ziabetes', 'ziabitees']],
  ['saans', ['saans', 'sans', 'saas']],
  ['kamar', ['kamar', 'kamr', 'kmr']],
  ['ulti', ['ulti', 'ulty', 'qay', 'qai', 'ultiyan', 'ultian']],
  ['dast', ['dast', 'dust', 'dastt']],
  ['chakkar', ['chakkar', 'chakar', 'chkkr']],
  ['kamzori', ['kamzori', 'kamzoori', 'kamzory']],
  ['takleef', ['takleef', 'taklif', 'takleaf', 'taklef']],
  ['mard', ['mard', 'aadmi', 'admi', 'larka', 'larkaa', 'ladka', 'mrd']],
  ['aurat', ['aurat', 'khatoon', 'larki', 'ladki', 'khawateen', 'aurath', 'orat']],
  ['umar', ['umar', 'umr', 'umer', 'ummar']],
  ['dr', ['dr', 'daktar', 'doctor', 'dactar', 'dakter', 'doc', 'dr.']],
  ['naam', ['naam', 'nam', 'name', 'naamm']],
  ['tareekh', ['tareekh', 'tarikh', 'tareek', 'tarekh', 'date']],
  ['wajah', ['wajah', 'waja', 'wjh', 'wajha', 'sabab', 'reason']],
  ['hidayat', ['hidayat', 'hidayaat', 'hidayaat', 'hidayaten', 'hidayatein', 'instructions', 'instruction']],
  ['pata', ['pata', 'pta', 'address']],
  ['jins', ['jins', 'gender']],
  ['muddat', ['muddat', 'mudat', 'arsa', 'arsah', 'duration']],
  // confirm / cancel / misc
  ['haan', ['haan', 'han', 'ha', 'hn', 'hanji', 'jihan', 'haanji', 'hanjee', 'haa']],
  ['ji', ['ji', 'jee', 'g']],
  ['theek', ['theek', 'thik', 'teek', 'theak', 'thek', 'theeek', 'thk']],
  ['sahi', ['sahi', 'sahih', 'sai', 'sahe']],
  ['bilkul', ['bilkul', 'bilkool', 'bilkl', 'bilkull']],
  ['zaroor', ['zaroor', 'zarur', 'zroor']],
  ['nahi', ['nahi', 'nahin', 'nhi', 'nahe', 'nahee', 'nahii', 'nhin', 'nahen']],
  ['na', ['na', 'naa']],
  ['rehne', ['rehne', 'rehnay', 'rehn', 'rahne', 'rahnay', 'rehney']],
  ['chhor', ['chhor', 'chor', 'choro', 'chhoro', 'chordo', 'chhordo', 'choor']],
  ['mat', ['mat', 'mt', 'matt']],
  ['khatam', ['khatam', 'khtm', 'khatm']],
  ['wapas', ['wapas', 'wapis', 'waapis', 'waapas', 'peeche', 'pichay', 'pichhe', 'peechay', 'piche', 'wapsi']],
  ['ghar', ['ghar', 'shuru', 'shuroo', 'ghr']],
  ['neeche', ['neeche', 'neechay', 'niche', 'nichay', 'neechey', 'nichey', 'neechy', 'nichy']],
  ['upar', ['upar', 'oopar', 'ooper', 'uper', 'upper', 'oper', 'ooppar']],
  ['sab', ['sab', 'sb', 'sabse', 'sbse']],
  ['akhir', ['akhir', 'aakhir', 'akheer', 'aakhri', 'akhri']],
  ['madad', ['madad', 'madat', 'mdd', 'help']],
  ['kya', ['kya', 'kia', 'kiya', 'kaya']],
  ['bol', ['bol', 'bolo', 'boal', 'keh', 'kah']],
  ['sakta', ['sakta', 'sakti', 'sakte', 'saktay', 'sakty', 'sakti', 'skta', 'skti', 'sktay']],
  ['muun', ['muun', 'munh', 'mun', 'mou', 'mooh', 'muh', 'mouth', 'moonh', 'munah']],
  ['nas', ['nas', 'naso', 'nason', 'nasein', 'naas']],
  ['lagane', ['lagane', 'laganay', 'lagany', 'lagaane']],
  ['malham', ['malham', 'marham', 'marhum', 'malhum', 'cream', 'creem']],
  ['aankh', ['aankh', 'ankh', 'aankhon', 'ankhon', 'aankho', 'aankhen']],
  ['kaan', ['kaan', 'kan', 'kaano', 'kaanon', 'kano']],
  ['naak', ['naak', 'nak', 'naakk']],
  ['qatre', ['qatre', 'qatray', 'katre', 'katray', 'drops', 'qatray', 'qatrey']],
  ['zuban', ['zuban', 'zaban', 'zabaan', 'zubaan']],
  ['har', ['har', 'hr', 'harr']],
  ['rozana', ['rozana', 'rozaana', 'rozanah']],
  ['jab', ['jab', 'jb']],
  ['ho', ['ho', 'hoo', 'hojaye', 'hojae']],
  ['mutabiq', ['mutabiq', 'mutabik', 'mutaabiq']],
  ['hone', ['hone', 'honay', 'honey']],
  ['tab', ['tab', 'taab']],
  ['field', ['field', 'feeld']],
  ['form', ['form', 'farm', 'foram']],
  ['file', ['file', 'fail', 'fyle']],
  ['record', ['record', 'rikard', 'rekard']],
  ['sidebar', ['sidebar', 'side-bar', 'menu', 'menyu']],
  ['section', ['section', 'hissa', 'hisse', 'hissay', 'hisay']],
  ['appointment', ['appointment', 'mulaqat', 'mulakat', 'apointment', 'appoinment', 'appointmnt', 'apoinment', 'appt']],
  ['book', ['book', 'buk']],
  ['peer', ['peer', 'somwar', 'somvar', 'monday', 'pir']],
  ['mangal', ['mangal', 'tuesday', 'mangl']],
  ['budh', ['budh', 'wednesday', 'bidh']],
  ['jumerat', ['jumerat', 'jumeraat', 'jumairat', 'thursday', 'jumaraat']],
  ['jumma', ['jumma', 'juma', 'jumah', 'friday', 'jummah']],
  ['sanichar', ['sanichar', 'saturday']],
  ['itwar', ['itwar', 'itvaar', 'itwaar', 'sunday', 'itvar']],
  ['phone', ['phone', 'fone', 'mobile', 'mobail', 'cell']],
  ['email', ['email', 'e-mail', 'imail']],
  ['ilaj', ['ilaj', 'ilaaj', 'treatment']],
  ['tashkhees', ['tashkhees', 'tashkhis', 'diagnosis', 'marz', 'bimari', 'bimaari']],
  ['allergy', ['allergy', 'alergy', 'allergi', 'elergy', 'alarji']],
  ['prescription', ['prescription', 'nuskha', 'nuskhah', 'prescrption', 'perscription', 'nusqa']],
  ['profile', ['profile', 'profail', 'profyle']],
  ['calendar', ['calendar', 'calender', 'kalendar', 'kalender']],
  ['dashboard', ['dashboard', 'dash-board', 'dashbord']],
  ['search', ['search', 'sarch', 'srch', 'talash', 'talaash', 'talaash']],
  ['tick', ['tick', 'tik', 'check']],
  ['untick', ['untick', 'untik', 'uncheck', 'unchek']],
  ['on', ['on', 'onn']],
  ['off', ['off', 'of']],
  ['submit', ['submit', 'sabmit', 'jama']],
  ['save', ['save', 'sev', 'sav']],
  ['cancel', ['cancel', 'cansel', 'cancle', 'kancel', 'mansookh']],
  ['close', ['close', 'clos', 'kloz']],
  ['select', ['select', 'selekt', 'silect']],
  ['clear', ['clear', 'kliyar', 'clr']],
  ['delete', ['delete', 'dilit', 'dlt']],
  ['remove', ['remove', 'rimoov']],
  ['set', ['set', 'sett']],
  ['scroll', ['scroll', 'skrol', 'scrol']],
  ['top', ['top', 'tap']],
  ['bottom', ['bottom', 'botam', 'botom']],
  ['register', ['register', 'rajistar', 'rejister', 'regstr']],
  ['add', ['add', 'ad', 'aad', 'shamil', 'shaamil']],
  ['show', ['show', 'sho']],
  ['open', ['open', 'opn', 'oppen']],
  ['home', ['home', 'hom']],
  ['back', ['back', 'bak']],
  ['amoxicillin', ['amoxicillin', 'amoxcillin', 'amoxicilin', 'amoxycillin', 'amoxil', 'amoxi', 'amoxicilline']],
  ['paracetamol', ['paracetamol', 'paracetmol', 'paracitamol', 'parasitamol', 'paracetamole']],
  ['ibuprofen', ['ibuprofen', 'ibuprofin', 'ibrufen', 'ibuprofine']],
  ['azithromycin', ['azithromycin', 'azithromycine', 'azithro', 'azithromicin']],
  ['metformin', ['metformin', 'metformine', 'metfarmin']],
  ['omeprazole', ['omeprazole', 'omeprazol', 'omiprazole']],
  ['ciprofloxacin', ['ciprofloxacin', 'ciprofloxacine', 'ciproflaxacin']],
  ['cefixime', ['cefixime', 'cefixim', 'sefixime']],
  ['mg', ['mg', 'milligram', 'milligrams', 'miligram', 'miligrams', 'mgs', 'emji', 'em-ji']],
  ['ml', ['ml', 'millilitre', 'milliliter', 'mililitre', 'mililiter', 'emel', 'em-el']],
  ['mcg', ['mcg', 'microgram', 'micrograms', 'mikrogram']],
  ['gram', ['gram', 'grams', 'gm', 'graam']],
];

// ---------------------------------------------------------------- urdu script -> canonical roman
const SCRIPT_WORDS: Array<[string, string[]]> = [
  // verbs
  ['jao', ['جاؤ', 'جائیں', 'جائے', 'جاو', 'جائو', 'جاؤں', 'جایں', 'جا']],
  ['jana', ['جانا', 'جاناہے']],
  ['chalo', ['چلو', 'چلیں', 'چلئے', 'چلیے', 'چل']],
  ['kholo', ['کھولو', 'کھولیں', 'کھولئے', 'کھولیے', 'کھول', 'کھولنا', 'کھولدو']],
  ['dikhao', ['دکھاؤ', 'دکھائیں', 'دکھائو', 'دکھاو', 'دکھا', 'دکھانا', 'دکھائیے', 'دکھادو']],
  ['karo', ['کرو', 'کریں', 'کیجئے', 'کیجیے', 'کردو', 'کر', 'کرنا', 'کریے', 'کرین']],
  ['do', ['دو']],
  ['daalo', ['ڈالو', 'ڈالیں', 'ڈال', 'ڈالدو', 'ڈالئے', 'ڈالیے']],
  ['likho', ['لکھو', 'لکھیں', 'لکھ', 'لکھدو', 'لکھئے', 'لکھیے']],
  ['banao', ['بناؤ', 'بنائیں', 'بناو', 'بنا', 'بنادو', 'بنائو', 'بنائیے']],
  ['dhoondo', ['ڈھونڈو', 'ڈھونڈیں', 'ڈھونڈ', 'تلاش', 'ڈھونڈھو', 'ڈھونڈھیں']],
  ['rakho', ['رکھو', 'رکھیں', 'رکھ', 'رکھدو', 'رکھئے']],
  ['hatao', ['ہٹاؤ', 'ہٹائیں', 'ہٹا', 'مٹاؤ', 'مٹائیں', 'ہٹادو', 'نکالو', 'نکال']],
  ['bhejo', ['بھیجو', 'بھیجیں', 'بھیج', 'بھیجدو']],
  ['roko', ['روکو', 'رکو', 'رک', 'روک']],
  ['band', ['بند']],
  ['chupao', ['چھپاؤ', 'چھپائیں', 'چھپا']],
  ['chuno', ['چنو', 'چنیں', 'چن']],
  ['bharo', ['بھرو', 'بھریں', 'بھر', 'بھردو']],
  ['lagao', ['لگاؤ', 'لگائیں', 'لگا', 'لگادو']],
  ['chahiye', ['چاہیے', 'چاہئے', 'چاہیئے', 'چاہتا', 'چاہتی', 'چاہتے']],
  ['hoon', ['ہوں', 'ہو']],
  ['hai', ['ہے', 'ہیں']],
  ['saaf', ['صاف']],
  ['khali', ['خالی']],
  ['mehfooz', ['محفوظ']],
  ['le', ['لے']],
  // particles
  ['par', ['پر', 'پہ', 'پے']],
  ['ko', ['کو']],
  ['ke', ['کے']],
  ['ka', ['کا']],
  ['ki', ['کی']],
  ['se', ['سے']],
  ['mein', ['میں', 'مے', 'مین']],
  ['tak', ['تک']],
  ['liye', ['لیے', 'لئے', 'لیئے', 'لیۓ']],
  ['saath', ['ساتھ']],
  ['baad', ['بعد']],
  ['pehle', ['پہلے', 'پہلے']],
  ['wala', ['والا', 'والی', 'والے']],
  ['mujhe', ['مجھے', 'مجھ']],
  ['zara', ['ذرا', 'پلیز', 'مہربانی', 'براہ', 'کرم']],
  ['naya', ['نیا', 'نئی', 'نئے', 'نیی']],
  ['aur', ['اور']],
  ['phir', ['پھر']],
  ['uske', ['اسکے', 'اس']],
  ['ab', ['اب', 'ابھی']],
  ['bhi', ['بھی']],
  ['hi', ['ہی']],
  ['ye', ['یہ', 'اسے', 'اسکو']],
  ['ek', ['ایک']],
  // nouns
  ['dawai', ['دوائی', 'دوا', 'دوائیں', 'دوایاں', 'دوائياں', 'دوایی', 'ادویات', 'میڈیسن', 'میڈیکیشن', 'میڈیکیشنز', 'میڈیسنز']],
  ['mareez', ['مریض', 'مریضوں', 'پیشنٹ', 'پیشینٹ', 'مریضہ']],
  ['page', ['پیج', 'صفحہ', 'صفحے', 'صفحا', 'سکرین', 'اسکرین']],
  ['number', ['نمبر', 'نمبرز']],
  ['dosage', ['خوراک', 'ڈوز', 'ڈوزیج', 'ڈوسیج']],
  ['din', ['دن', 'دنوں', 'روز', 'دنو']],
  ['hafta', ['ہفتہ', 'ہفتے', 'ہفتوں', 'ہفتا']],
  ['mahina', ['مہینہ', 'مہینے', 'مہینوں', 'مہینا', 'ماہ']],
  ['saal', ['سال', 'سالوں', 'برس']],
  ['ghanta', ['گھنٹہ', 'گھنٹے', 'گھنٹوں', 'گھنٹا']],
  ['baje', ['بجے', 'بجے', 'بجے']],
  ['subah', ['صبح', 'سویرے']],
  ['shaam', ['شام']],
  ['dopahar', ['دوپہر']],
  ['raat', ['رات']],
  ['kal', ['کل']],
  ['aaj', ['آج']],
  ['parso', ['پرسوں', 'پرسو']],
  ['agle', ['اگلے', 'اگلا', 'اگلی']],
  ['bar', ['بار', 'دفعہ', 'مرتبہ', 'باری']],
  ['waqt', ['وقت']],
  ['tablet', ['گولی', 'گولیاں', 'ٹیبلٹ', 'ٹیبلیٹ', 'گولیوں']],
  ['capsule', ['کیپسول', 'کپسول']],
  ['syrup', ['شربت', 'سیرپ']],
  ['injection', ['ٹیکہ', 'انجکشن', 'انجیکشن', 'سوئی', 'ٹیکا']],
  ['khana', ['کھانا', 'کھانے', 'کھانی']],
  ['sone', ['سونے', 'سوتے']],
  ['zaroorat', ['ضرورت']],
  ['bukhar', ['بخار']],
  ['dard', ['درد']],
  ['sar', ['سر']],
  ['khansi', ['کھانسی']],
  ['zukam', ['زکام', 'نزلہ', 'نزله']],
  ['gala', ['گلا', 'گلے']],
  ['kharab', ['خراب']],
  ['pait', ['پیٹ']],
  ['seena', ['سینہ', 'سینے', 'چھاتی']],
  ['sugar', ['شوگر', 'شکر', 'ذیابیطس']],
  ['saans', ['سانس']],
  ['kamar', ['کمر']],
  ['ulti', ['الٹی', 'قے', 'الٹیاں']],
  ['dast', ['دست']],
  ['chakkar', ['چکر']],
  ['kamzori', ['کمزوری']],
  ['takleef', ['تکلیف']],
  ['mard', ['مرد', 'آدمی', 'لڑکا']],
  ['aurat', ['عورت', 'خاتون', 'لڑکی', 'خواتین']],
  ['umar', ['عمر']],
  ['dr', ['ڈاکٹر', 'ڈاکٹرصاحب', 'داکٹر']],
  ['naam', ['نام']],
  ['tareekh', ['تاریخ', 'ڈیٹ']],
  ['wajah', ['وجہ', 'سبب']],
  ['hidayat', ['ہدایت', 'ہدایات']],
  ['pata', ['پتہ', 'پتا', 'ایڈریس']],
  ['jins', ['جنس', 'جینڈر']],
  ['muddat', ['مدت', 'عرصہ']],
  // confirm / cancel / misc
  ['haan', ['ہاں', 'ہان', 'جی', 'جیہاں']],
  ['ji', ['جی']],
  ['theek', ['ٹھیک', 'ٹهیک']],
  ['sahi', ['صحیح', 'سہی']],
  ['bilkul', ['بالکل', 'بلکل']],
  ['zaroor', ['ضرور']],
  ['nahi', ['نہیں', 'نہی', 'نہ', 'نا']],
  ['rehne', ['رہنے']],
  ['chhor', ['چھوڑ', 'چھوڑو', 'چھوڑدو', 'چھوڑیں']],
  ['mat', ['مت']],
  ['khatam', ['ختم']],
  ['wapas', ['واپس', 'پیچھے', 'واپسی']],
  ['ghar', ['گھر', 'شروع', 'ہوم']],
  ['neeche', ['نیچے']],
  ['upar', ['اوپر', 'اُوپر']],
  ['sab', ['سب', 'سبسے']],
  ['akhir', ['آخر', 'آخری']],
  ['madad', ['مدد', 'ہیلپ']],
  ['kya', ['کیا']],
  ['bol', ['بول', 'بولو', 'کہہ', 'کہ']],
  ['sakta', ['سکتا', 'سکتی', 'سکتے']],
  ['muun', ['منہ', 'مونہ', 'منھ']],
  ['nas', ['نس', 'نسوں', 'ڈرپ']],
  ['lagane', ['لگانے', 'لگانی']],
  ['malham', ['مرہم', 'ملہم', 'کریم']],
  ['aankh', ['آنکھ', 'آنکھوں', 'آنکھیں']],
  ['kaan', ['کان', 'کانوں']],
  ['naak', ['ناک']],
  ['qatre', ['قطرے', 'ڈراپس']],
  ['zuban', ['زبان']],
  ['har', ['ہر']],
  ['rozana', ['روزانہ']],
  ['jab', ['جب']],
  ['ho', ['ہو']],
  ['mutabiq', ['مطابق']],
  ['hone', ['ہونے']],
  ['tab', ['ٹیب']],
  ['field', ['فیلڈ']],
  ['form', ['فارم']],
  ['file', ['فائل']],
  ['record', ['ریکارڈ']],
  ['sidebar', ['سائیڈبار', 'مینو', 'مینیو']],
  ['section', ['سیکشن', 'حصہ', 'حصے']],
  ['appointment', ['اپائنٹمنٹ', 'اپوائنٹمنٹ', 'ملاقات', 'اپائینٹمنٹ', 'اپوائینٹمنٹ']],
  ['book', ['بک']],
  ['peer', ['پیر', 'سوموار']],
  ['mangal', ['منگل']],
  ['budh', ['بدھ']],
  ['jumerat', ['جمعرات']],
  ['jumma', ['جمعہ', 'جمعے']],
  ['sanichar', ['ہفتہ‌کادن', 'سنیچر']],
  ['itwar', ['اتوار']],
  ['phone', ['فون', 'موبائل', 'نمبرفون']],
  ['email', ['ایمیل', 'ای‌میل']],
  ['ilaj', ['علاج']],
  ['tashkhees', ['تشخیص', 'مرض', 'بیماری']],
  ['allergy', ['الرجی', 'الرجیز', 'الرجیاں']],
  ['prescription', ['نسخہ', 'نسخے', 'پریسکرپشن', 'پرسکرپشن']],
  ['profile', ['پروفائل']],
  ['calendar', ['کیلنڈر', 'کلینڈر']],
  ['dashboard', ['ڈیش‌بورڈ', 'ڈیشبورڈ', 'ڈیش', 'بورڈ']],
  ['search', ['سرچ']],
  ['tick', ['ٹک', 'چیک']],
  ['untick', ['انٹک', 'انچیک']],
  ['on', ['آن']],
  ['off', ['آف']],
  ['submit', ['سبمٹ', 'جمع']],
  ['save', ['سیو', 'محفوظ']],
  ['cancel', ['کینسل', 'منسوخ']],
  ['close', ['کلوز']],
  ['select', ['سلیکٹ', 'منتخب']],
  ['clear', ['کلیئر', 'کلیر']],
  ['delete', ['ڈیلیٹ']],
  ['remove', ['ریموو']],
  ['set', ['سیٹ']],
  ['scroll', ['سکرول', 'اسکرول']],
  ['top', ['ٹاپ']],
  ['bottom', ['باٹم']],
  ['register', ['رجسٹر']],
  ['add', ['ایڈ', 'شامل']],
  ['show', ['شو']],
  ['open', ['اوپن']],
  ['home', ['ہوم']],
  ['back', ['بیک']],
  ['mg', ['ملیگرام', 'ملی‌گرام', 'ایمجی', 'ایم‌جی', 'ملیگرم']],
  ['ml', ['ملیلیٹر', 'ملی‌لیٹر', 'ایمایل']],
  ['mili', ['ملی']],
  ['gram', ['گرام']],
  ['mcg', ['مائیکروگرام']],
  ['gram', ['گرام']],
  ['patient', ['پیشنٹس']],
  ['medications', ['میڈیکیشنز']],
  ['allergies', ['الرجیز']],
  ['insurance', ['انشورنس', 'انشورینس']],
  ['history', ['ہسٹری', 'تاریخچہ']],
  ['problems', ['پرابلمز', 'مسائل']],
  ['documents', ['ڈاکومنٹس', 'دستاویزات']],
  ['notes', ['نوٹس']],
  ['note', ['نوٹ']],
  ['user', ['یوزر']],
  ['users', ['یوزرز']],
  ['management', ['مینجمنٹ', 'مینیجمنٹ']],
  ['settings', ['سیٹنگز', 'ترتیبات', 'سیٹنگ']],
  ['reports', ['رپورٹس', 'رپورٹ']],
  ['roster', ['روسٹر']],
  ['shift', ['شفٹ']],
  ['leave', ['چھٹی', 'لیو']],
  ['provider', ['پرووائیڈر', 'پروائیڈر']],
  ['providers', ['پرووائیڈرز', 'پروائیڈرز']],
  ['practice', ['پریکٹس']],
  ['queue', ['کیو', 'قطار']],
  ['lab', ['لیب', 'لیبارٹری']],
  ['labs', ['لیبز']],
  ['imaging', ['امیجنگ']],
  ['referral', ['ریفرل', 'ریفرال']],
  ['referrals', ['ریفرلز']],
  ['consultation', ['کنسلٹیشن', 'مشاورت']],
  ['summary', ['سمری', 'خلاصہ']],
  ['demographics', ['ڈیموگرافکس']],
  ['immunizations', ['امیونائزیشنز', 'ویکسینیشن', 'ویکسین']],
  ['contacts', ['کانٹیکٹس', 'رابطے']],
  ['communication', ['کمیونیکیشن']],
  ['route', ['روٹ']],
  ['frequency', ['فریکوئنسی', 'فریکوینسی']],
  ['duration', ['ڈیوریشن']],
  ['refills', ['ریفلز', 'ریفل']],
  ['quantity', ['کوانٹٹی', 'مقدار', 'تعداد']],
  ['pharmacy', ['فارمیسی']],
  ['severity', ['سیویریٹی', 'شدت']],
  ['mild', ['مائلڈ', 'ہلکی', 'ہلکا']],
  ['moderate', ['موڈریٹ', 'درمیانی']],
  ['severe', ['سیویئر', 'شدید']],
  ['urgent', ['ارجنٹ', 'فوری']],
  ['penicillin', ['پینسلن', 'پنسلین', 'پینیسیلین']],
  ['amoxicillin', ['اموکسیسلن', 'اموکسیلین', 'اموکسیسیلین', 'اموکسیسلین', 'اموکسلین', 'ایموکسیسلین', 'اموکسی']],
  ['paracetamol', ['پیراسیٹامول', 'پیراسٹامول', 'پیراسیٹمول']],
  ['panadol', ['پیناڈول', 'پناڈول']],
  ['ibuprofen', ['آئبوپروفین', 'ایبوپروفین', 'آئی‌بوپروفین']],
  ['brufen', ['بروفن']],
  ['metformin', ['میٹفارمن', 'میٹفورمن']],
  ['azithromycin', ['ازیتھرومائسن', 'ایزیتھرومائسین', 'ازیتھرومائیسن']],
  ['ciprofloxacin', ['سپروفلوکساسن', 'سیپروفلوکساسین']],
  ['omeprazole', ['اومیپرازول', 'اومپرازول']],
  ['augmentin', ['آگمنٹن', 'اگمنٹن', 'آگمینٹن']],
  ['cefixime', ['سیفکسیم', 'سفکسیم']],
  ['atorvastatin', ['اٹورواسٹیٹن', 'ایٹورواسٹیٹن']],
  ['amlodipine', ['املوڈیپین', 'ایملوڈیپین']],
  ['losartan', ['لوسارٹن']],
  ['insulin', ['انسولین']],
  ['lisinopril', ['لیزینوپرل', 'لسینوپرل']],
  ['aspirin', ['اسپرین', 'ایسپرین', 'ڈسپرین']],
  ['disprin', ['ڈسپرن']],
  ['flagyl', ['فلیجل']],
  ['metronidazole', ['میٹرونیڈازول']],
  ['clavulanate', ['کلاولانیٹ']],
  ['orally', ['اورلی']],
  ['twice', ['ٹوائس']],
  ['daily', ['ڈیلی']],
  ['once', ['ونس']],
  ['for', ['فار']],
  ['and', ['اینڈ']],
  ['to', ['ٹو']],
  ['go', ['گو']],
  ['the', ['دی']],
  ['john', ['جان']],
  ['smith', ['سمتھ']],
  ['ahmed', ['احمد']],
  ['khan', ['خان']],
  ['sarah', ['سارہ', 'سارا']],
  ['bilal', ['بلال']],
  ['hussain', ['حسین']],
  ['ali', ['علی']],
  ['fatima', ['فاطمہ']],
  ['ayesha', ['عائشہ']],
  ['hassan', ['حسن']],
  ['usman', ['عثمان']],
  ['maria', ['ماریہ']],
  ['zainab', ['زینب']],
  ['imran', ['عمران']],
  ['sana', ['ثنا']],
  ['omar', ['عمر']],
];

/** Urdu-script token -> canonical Roman token (or digit string). */
export const SCRIPT: Record<string, string> = {};
/** Roman spelling variant -> canonical Roman token (or digit string). */
export const ROMAN: Record<string, string> = {};

for (const [n, spellings] of SCRIPT_NUMBERS) for (const s of spellings) SCRIPT[s] = String(n);
for (const [canonical, spellings] of SCRIPT_WORDS) for (const s of spellings) if (!SCRIPT[s]) SCRIPT[s] = canonical;
for (const [n, spellings] of ROMAN_NUMBERS) for (const s of spellings) ROMAN[s] = String(n);
for (const [canonical, spellings] of ROMAN_VARIANTS) for (const s of spellings) if (!ROMAN[s]) ROMAN[s] = canonical;
// "sat"/"saat" are far more often the number seven than "with"; "ke saath"/"ke sath" is handled as a phrase.
ROMAN.sat = '7';
ROMAN.saat = '7';
ROMAN.saath = 'saath';
ROMAN.sath = 'saath';

/**
 * Canonical Roman tokens that only occur in Urdu. Their presence (or any Urdu-script
 * character) switches the translator on; without one the transcript is passed through
 * untouched so ordinary English commands are never rewritten.
 */
export const URDU_MARKERS = new Set<string>([
  'jao', 'jana', 'chalo', 'kholo', 'dikhao', 'karo', 'daalo', 'likho', 'banao', 'dhoondo', 'rakho', 'hatao', 'bhejo', 'roko', 'chupao', 'chuno', 'bharo', 'lagao', 'chahiye', 'hoon', 'hai', 'saaf', 'khali', 'mehfooz',
  'par', 'ko', 'ke', 'ka', 'ki', 'mein', 'tak', 'liye', 'saath', 'baad', 'pehle', 'wala', 'mujhe', 'zara', 'naya', 'aur', 'phir', 'uske', 'bhi',
  'dawai', 'mareez', 'din', 'hafta', 'mahina', 'saal', 'ghanta', 'baje', 'subah', 'shaam', 'dopahar', 'raat', 'kal', 'aaj', 'parso', 'agle', 'bar', 'waqt', 'khana', 'sone', 'zaroorat',
  'bukhar', 'dard', 'khansi', 'zukam', 'gala', 'kharab', 'pait', 'seena', 'saans', 'kamar', 'ulti', 'dast', 'chakkar', 'kamzori', 'takleef', 'mard', 'aurat', 'umar', 'naam', 'tareekh', 'wajah', 'hidayat', 'pata', 'jins', 'muddat',
  'haan', 'ji', 'theek', 'sahi', 'bilkul', 'zaroor', 'nahi', 'rehne', 'chhor', 'mat', 'khatam', 'wapas', 'ghar', 'neeche', 'upar', 'akhir', 'madad', 'kya', 'sakta', 'muun', 'nas', 'lagane', 'malham', 'aankh', 'kaan', 'naak', 'qatre', 'zuban', 'har', 'rozana', 'jab', 'mutabiq', 'hone',
  'mulaqat', 'peer', 'mangal', 'budh', 'jumerat', 'jumma', 'sanichar', 'itwar', 'ilaj', 'tashkhees', 'nuskha',
  // raw Roman spellings whose canonical form is an English word
  'kar', 'nuskhah', 'mulakat', 'safha', 'safa', 'khuraak', 'khurak', 'khoraak', 'goli', 'goliyan', 'sharbat', 'teeka', 'tika', 'madat', 'shuru', 'hissa', 'hisse', 'chhutti', 'mehfooz', 'mansookh', 'shamil', 'bimari', 'marz', 'talash', 'talaash', 'nam', 'hidayaat', 'arsa', 'kapsool', 'daktar', 'dactar', 'kalendar', 'rajistar', 'sabmit', 'kro', 'kardo', 'krdo', 'kholdo', 'dikhado', 'bnao', 'wapis',
]);

/**
 * Raw (pre-canonical) Roman spellings that must NOT count as Urdu markers even though
 * they canonicalise to a marker — they are ordinary English words in commands.
 */
export const AMBIGUOUS_ROMAN = new Set(['me', 'main', 'may', 'men', 'is', 'us', 'use', 'on', 'of', 'or', 'ur', 'do', 'no', 'to', 'so', 'sat', 'g', 'k', 'ja', 'ha', 'ho', 'hi', 'bi', 'ab', 'ad', 'bad', 'pay', 'per', 'say', 'help', 'please', 'name', 'date', 'reason', 'address', 'gender', 'duration', 'instructions', 'instruction', 'treatment', 'diagnosis', 'check', 'menu', 'mobile', 'cell', 'phone', 'email', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'mouth', 'cream', 'drops', 'tablet', 'tablets', 'capsule', 'capsules', 'syrup', 'injection', 'dose', 'dosage', 'page', 'number', 'num', 'tab', 'field', 'form', 'file', 'record', 'sidebar', 'section', 'appointment', 'book', 'allergy', 'allergies', 'prescription', 'profile', 'calendar', 'dashboard', 'search', 'tick', 'untick', 'uncheck', 'off', 'submit', 'save', 'cancel', 'close', 'select', 'clear', 'delete', 'remove', 'set', 'scroll', 'top', 'bottom', 'register', 'add', 'show', 'open', 'home', 'back', 'mg', 'ml', 'mcg', 'gram', 'grams', 'milligram', 'milligrams', 'microgram', 'micrograms', 'sar', 'sir', 'sugar', 'dust', 'pet', 'gala', 'kal', 'ban', 'band', 'bar', 'din', 'sal', 'rat', 'sham', 'saal']);
