import type { ThemeConfig } from 'antd';
import { colors, radius, typography } from './tokens';

/**
 * Ant Design theme. Mirrors the CSS variables in styles/global.css so antd
 * components and hand-written markup share one visual language.
 */
export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    colorText: colors.text,
    colorTextSecondary: colors.textSecondary,
    colorTextTertiary: colors.textMuted,
    colorTextPlaceholder: '#98a4b0',
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    colorBgLayout: colors.surfaceMuted,
    colorBgContainer: colors.surface,
    colorBgElevated: colors.surface,
    colorFillSecondary: '#eef2f6',
    colorFillTertiary: '#f3f6f9',
    colorFillQuaternary: '#f7f9fb',
    borderRadius: radius.md,
    borderRadiusLG: radius.lg,
    borderRadiusSM: radius.sm,
    borderRadiusXS: 4,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.md,
    fontSizeSM: typography.sizes.sm,
    fontSizeLG: typography.sizes.lg,
    lineHeight: 1.5,
    controlHeight: 38,
    controlHeightSM: 30,
    controlHeightLG: 46,
    controlOutlineWidth: 3,
    controlOutline: 'rgba(15, 110, 140, 0.18)',
    boxShadow: '0 2px 8px rgba(16, 24, 40, 0.08)',
    boxShadowSecondary: '0 8px 24px rgba(16, 24, 40, 0.12)',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.16s',
    motionDurationSlow: '0.22s',
    wireframe: false,
  },
  components: {
    Layout: {
      siderBg: colors.sidebar,
      headerBg: colors.surface,
      headerHeight: 60,
      headerPadding: '0 16px',
      bodyBg: colors.surfaceMuted,
    },
    Menu: {
      darkItemBg: colors.sidebar,
      darkSubMenuItemBg: '#0a1821',
      darkItemColor: colors.sidebarText,
      darkItemHoverBg: 'rgba(255,255,255,0.07)',
      darkItemHoverColor: '#ffffff',
      darkItemSelectedBg: colors.primary,
      darkItemSelectedColor: '#ffffff',
      darkGroupTitleColor: '#7f94a4',
      itemBorderRadius: radius.sm,
      itemMarginInline: 10,
      itemMarginBlock: 2,
      itemHeight: 40,
      iconSize: 16,
      collapsedIconSize: 18,
    },
    Card: {
      headerFontSize: 15,
      headerFontSizeSM: 14,
      headerHeight: 54,
      headerHeightSM: 44,
      paddingLG: 20,
      bodyPadding: 20,
      bodyPaddingSM: 14,
      colorBorderSecondary: colors.border,
    },
    Table: {
      headerBg: colors.surfaceSubtle,
      headerColor: colors.textSecondary,
      headerSortActiveBg: '#eef2f6',
      headerSortHoverBg: '#eef2f6',
      rowHoverBg: '#f2f7fa',
      rowSelectedBg: '#e6f3f7',
      rowSelectedHoverBg: '#d9ecf3',
      cellPaddingBlock: 12,
      cellPaddingInline: 14,
      cellPaddingBlockMD: 10,
      cellPaddingInlineMD: 12,
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 10,
      headerBorderRadius: radius.md,
      footerBg: colors.surfaceSubtle,
    },
    Form: {
      labelColor: colors.text,
      labelFontSize: 13,
      labelHeight: 22,
      verticalLabelPadding: '0 0 6px',
      itemMarginBottom: 18,
      labelRequiredMarkColor: colors.error,
    },
    Input: { paddingInline: 12, hoverBorderColor: colors.primaryHover, activeBorderColor: colors.primary },
    InputNumber: { paddingInline: 12 },
    Select: { optionSelectedBg: colors.primarySoft, optionPadding: '8px 12px', optionHeight: 36 },
    DatePicker: { cellHeight: 30, cellWidth: 34 },
    Button: {
      fontWeight: 500,
      paddingInline: 16,
      paddingInlineSM: 12,
      primaryShadow: '0 1px 2px rgba(15, 110, 140, 0.25)',
      defaultShadow: '0 1px 2px rgba(16, 24, 40, 0.05)',
      dangerShadow: '0 1px 2px rgba(214, 69, 69, 0.2)',
      defaultBorderColor: colors.borderStrong,
      defaultHoverBorderColor: colors.primary,
      defaultHoverColor: colors.primary,
      contentFontSizeSM: 13,
    },
    Tabs: { horizontalItemPadding: '10px 2px', titleFontSize: 14, horizontalMargin: '0 0 16px 0', inkBarColor: colors.primary, itemHoverColor: colors.primary, horizontalItemGutter: 24 },
    Modal: {
      titleFontSize: 17,
      titleLineHeight: 1.4,
      headerBg: colors.surface,
      contentBg: colors.surface,
      footerBg: colors.surfaceSubtle,
      borderRadiusLG: radius.xl,
    },
    Tag: { borderRadiusSM: 6, defaultBg: '#f1f4f7', defaultColor: colors.textSecondary },
    Statistic: { titleFontSize: 12, contentFontSize: 22 },
    Breadcrumb: { itemColor: colors.textMuted, lastItemColor: colors.textSecondary, linkColor: colors.textMuted, linkHoverColor: colors.primary, separatorMargin: 6, fontSize: 12 },
    Steps: { titleLineHeight: 28, descriptionMaxWidth: 160 },
    Alert: { defaultPadding: '10px 14px', withDescriptionPadding: '14px 16px' },
    Descriptions: { labelBg: colors.surfaceSubtle, itemPaddingBottom: 8 },
    Segmented: { itemSelectedBg: colors.surface, trackBg: '#eef2f6', itemSelectedColor: colors.text },
    Tooltip: { colorBgSpotlight: '#1a2733', fontSize: 12.5 },
    Dropdown: { paddingBlock: 6 },
    Popover: { titleMinWidth: 200 },
    Message: { contentPadding: '10px 16px' },
    Switch: { trackHeight: 22, handleSize: 18, trackMinWidth: 40 },
    Checkbox: { borderRadiusSM: 4 },
    Skeleton: { gradientFromColor: '#eef2f6', gradientToColor: '#f7f9fb' },
    Progress: { defaultColor: colors.primary, remainingColor: '#eef2f6' },
    Timeline: { dotBg: colors.surface, tailColor: colors.border },
    Collapse: { headerPadding: '10px 14px', contentPadding: '12px 14px', headerBg: colors.surfaceSubtle },
    Empty: { colorTextDisabled: colors.textMuted },
  },
};
