import type { ThemeConfig } from 'antd';
import { colors, radius, typography } from './tokens';

/**
 * Ant Design theme. Mirrors the CSS variables in styles/global.css so antd
 * components and hand-written markup share one visual language: soft filled
 * fields, pill buttons, rounded cards and wide low-contrast shadows.
 */
export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    // Links are small text: the deeper azure keeps them readable (5.8:1 on white; #0780d8 is 4.1:1).
    colorLink: colors.primaryActive,
    colorLinkHover: colors.primary,
    colorText: colors.text,
    colorTextHeading: colors.ink,
    colorTextSecondary: colors.textSecondary,
    colorTextTertiary: colors.textMuted,
    colorTextPlaceholder: '#9aa1b3',
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    colorSplit: colors.border,
    colorBgLayout: colors.surfaceMuted,
    colorBgContainer: colors.surface,
    colorBgElevated: colors.surface,
    colorFillSecondary: '#eceef5',
    colorFillTertiary: '#f1f3f8',
    colorFillQuaternary: '#f6f7fb',
    borderRadius: radius.md,
    borderRadiusLG: radius.lg,
    borderRadiusSM: radius.sm,
    borderRadiusXS: 6,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.md,
    fontSizeSM: typography.sizes.sm,
    fontSizeLG: typography.sizes.lg,
    lineHeight: 1.5,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 48,
    controlOutlineWidth: 3,
    controlOutline: 'rgba(7, 128, 216, 0.16)',
    boxShadow: '0 2px 6px rgba(11,16,32,0.04), 0 10px 28px rgba(11,16,32,0.07)',
    boxShadowSecondary: '0 8px 20px rgba(11,16,32,0.07), 0 28px 56px rgba(11,16,32,0.12)',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.18s',
    motionDurationSlow: '0.26s',
    wireframe: false,
  },
  components: {
    Layout: {
      siderBg: colors.sidebar,
      headerBg: 'transparent',
      headerHeight: 64,
      headerPadding: '0 16px',
      bodyBg: colors.surfaceMuted,
    },
    Menu: {
      itemBg: 'transparent',
      subMenuItemBg: 'transparent',
      itemColor: colors.textSecondary,
      itemHoverBg: colors.surfaceMuted,
      itemHoverColor: colors.ink,
      itemSelectedBg: colors.primary,
      itemSelectedColor: '#ffffff',
      itemActiveBg: colors.primarySoft,
      groupTitleColor: colors.textMuted,
      itemBorderRadius: 14,
      itemMarginInline: 12,
      itemMarginBlock: 4,
      itemHeight: 46,
      iconSize: 18,
      collapsedIconSize: 19,
      activeBarBorderWidth: 0,
    },
    Card: {
      headerFontSize: 15,
      headerFontSizeSM: 14,
      headerHeight: 58,
      headerHeightSM: 46,
      paddingLG: 22,
      bodyPadding: 22,
      bodyPaddingSM: 16,
      colorBorderSecondary: colors.border,
      borderRadiusLG: radius.xl,
    },
    Table: {
      headerBg: colors.surfaceSubtle,
      headerColor: colors.textMuted,
      headerSortActiveBg: '#eef0f6',
      headerSortHoverBg: '#eef0f6',
      rowHoverBg: '#f4f9fe',
      rowSelectedBg: colors.primarySoft,
      rowSelectedHoverBg: '#d2eafb',
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellPaddingBlockMD: 12,
      cellPaddingInlineMD: 14,
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 10,
      headerBorderRadius: radius.md,
      footerBg: colors.surfaceSubtle,
      borderColor: '#eef0f5',
    },
    Form: {
      labelColor: colors.text,
      labelFontSize: 13,
      labelHeight: 22,
      verticalLabelPadding: '0 0 6px',
      itemMarginBottom: 18,
      labelRequiredMarkColor: colors.error,
    },
    Input: {
      paddingInline: 14,
      hoverBorderColor: colors.borderStrong,
      activeBorderColor: colors.primary,
      activeShadow: '0 0 0 4px rgba(7, 128, 216, 0.12)',
    },
    InputNumber: { paddingInline: 14, activeShadow: '0 0 0 4px rgba(7, 128, 216, 0.12)' },
    Select: {
      optionSelectedBg: colors.primarySoft,
      optionSelectedColor: colors.primaryActive,
      optionSelectedFontWeight: 600,
      optionActiveBg: colors.surfaceMuted,
      optionPadding: '9px 12px',
      optionHeight: 38,
      activeOutlineColor: 'rgba(7, 128, 216, 0.12)',
    },
    DatePicker: { cellHeight: 30, cellWidth: 34, activeShadow: '0 0 0 4px rgba(7, 128, 216, 0.12)' },
    Button: {
      fontWeight: 600,
      paddingInline: 18,
      paddingInlineSM: 12,
      borderRadius: 12,
      borderRadiusSM: 10,
      borderRadiusLG: 14,
      primaryShadow: '0 4px 14px rgba(7, 128, 216, 0.28)',
      defaultShadow: '0 1px 2px rgba(11, 16, 32, 0.04)',
      dangerShadow: '0 4px 14px rgba(229, 72, 77, 0.22)',
      defaultBorderColor: colors.border,
      defaultHoverBorderColor: colors.primary,
      defaultHoverColor: colors.primary,
      defaultBg: colors.surface,
      contentFontSizeSM: 13,
    },
    Radio: {
      buttonSolidCheckedBg: colors.primary,
      buttonSolidCheckedHoverBg: colors.primaryHover,
      buttonSolidCheckedActiveBg: colors.primaryActive,
      buttonBg: colors.surface,
      buttonCheckedBg: colors.primarySoft,
      buttonColor: colors.textSecondary,
    },
    Tabs: {
      horizontalItemPadding: '10px 2px',
      titleFontSize: 14,
      horizontalMargin: '0 0 16px 0',
      inkBarColor: colors.primary,
      itemHoverColor: colors.primary,
      itemSelectedColor: colors.primaryActive,
      horizontalItemGutter: 24,
    },
    Modal: {
      titleFontSize: 17,
      titleLineHeight: 1.4,
      headerBg: colors.surface,
      contentBg: colors.surface,
      footerBg: colors.surfaceSubtle,
      borderRadiusLG: radius.xl,
    },
    Tag: { borderRadiusSM: 999, defaultBg: '#f1f3f8', defaultColor: colors.textSecondary },
    Statistic: { titleFontSize: 12, contentFontSize: 22 },
    Breadcrumb: { itemColor: colors.textMuted, lastItemColor: colors.textSecondary, linkColor: colors.textMuted, linkHoverColor: colors.primary, separatorMargin: 6, fontSize: 12 },
    Steps: { titleLineHeight: 28, descriptionMaxWidth: 160 },
    Alert: { defaultPadding: '12px 16px', withDescriptionPadding: '16px 18px', borderRadiusLG: radius.md },
    Descriptions: { labelBg: colors.surfaceSubtle, itemPaddingBottom: 8 },
    Segmented: {
      itemSelectedBg: colors.surface,
      trackBg: '#eceef5',
      itemSelectedColor: colors.ink,
      itemColor: colors.textSecondary,
      itemHoverColor: colors.ink,
      trackPadding: 3,
      borderRadius: 12,
      borderRadiusSM: 10,
    },
    Tooltip: { colorBgSpotlight: '#161b2e', fontSize: 12.5, borderRadius: 10 },
    Dropdown: { paddingBlock: 7, borderRadiusLG: 14, borderRadiusSM: 10 },
    Popover: { titleMinWidth: 200, borderRadiusLG: 16 },
    Message: { contentPadding: '11px 18px' },
    Switch: { trackHeight: 24, handleSize: 20, trackMinWidth: 44 },
    Skeleton: { gradientFromColor: '#eceef5', gradientToColor: '#f6f7fb', borderRadiusSM: 8 },
    Progress: { defaultColor: colors.primary, remainingColor: '#eceef5' },
    Timeline: { dotBg: colors.surface, tailColor: colors.border },
    Collapse: { headerPadding: '12px 16px', contentPadding: '14px 16px', headerBg: colors.surfaceSubtle, borderRadiusLG: radius.lg },
    Empty: { colorTextDisabled: colors.textMuted },
    Pagination: { itemActiveBg: colors.primarySoft, borderRadius: 10 },
    Badge: { dotSize: 8 },
    Slider: { handleColor: colors.primary, trackBg: colors.primary, trackHoverBg: colors.primaryHover, railBg: '#e3e6ef', railHoverBg: '#d9dde9' },
  },
};
