import type { ThemeConfig } from 'antd';
import { colors, radius, typography } from './tokens';

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: colors.primary,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.error,
    colorInfo: colors.info,
    colorText: colors.text,
    colorTextSecondary: colors.textSecondary,
    colorTextTertiary: colors.textMuted,
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    colorBgLayout: colors.surfaceMuted,
    colorBgContainer: colors.surface,
    borderRadius: radius.md,
    borderRadiusLG: radius.lg,
    borderRadiusSM: radius.sm,
    fontFamily: typography.fontFamily,
    fontSize: typography.sizes.md,
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
    boxShadow: '0 2px 8px rgba(16, 24, 40, 0.08)',
    boxShadowSecondary: '0 8px 24px rgba(16, 24, 40, 0.12)',
    wireframe: false,
  },
  components: {
    Layout: {
      siderBg: colors.sidebar,
      headerBg: colors.surface,
      headerHeight: 60,
      headerPadding: '0 20px',
      bodyBg: colors.surfaceMuted,
    },
    Menu: {
      darkItemBg: colors.sidebar,
      darkSubMenuItemBg: '#0a1821',
      darkItemColor: colors.sidebarText,
      darkItemHoverBg: 'rgba(255,255,255,0.06)',
      darkItemSelectedBg: colors.primary,
      darkItemSelectedColor: '#ffffff',
      itemBorderRadius: radius.sm,
      itemMarginInline: 8,
      iconSize: 16,
    },
    Card: { headerFontSize: 15, headerHeight: 52, paddingLG: 20 },
    Table: {
      headerBg: colors.surfaceSubtle,
      headerColor: colors.textSecondary,
      rowHoverBg: '#f2f7fa',
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      headerBorderRadius: radius.md,
    },
    Form: {
      labelColor: colors.textSecondary,
      labelFontSize: 13,
      verticalLabelPadding: '0 0 4px',
      itemMarginBottom: 16,
    },
    Tabs: { horizontalItemPadding: '10px 0', titleFontSize: 14 },
    Drawer: { paddingLG: 20 },
    Modal: { titleFontSize: 16 },
    Tag: { borderRadiusSM: 4 },
    Statistic: { titleFontSize: 13, contentFontSize: 24 },
  },
};
