/**
 * A spoken/written overview of a patient, built only from the records that
 * exist. Nothing here is generated by a language model, so the summary can
 * never contain a medication, diagnosis, task, recall or appointment the
 * patient does not have.
 */
import dayjs from 'dayjs';
import type { Appointment, Diagnosis, Medication, Patient, Recall, Task } from '@/types/domain';

export interface NarrativeInput {
  patient: Patient;
  medications: Medication[];
  diagnoses: Diagnosis[];
  tasks: Task[];
  recalls: Recall[];
  appointments: Appointment[];
}

export interface PatientNarrative {
  /** One paragraph, suitable for reading aloud. */
  text: string;
  /** The same content as labelled sections, for the screen. */
  sections: Array<{ title: string; body: string }>;
}

const list = (items: string[], max = 4): string => {
  const shown = items.slice(0, max);
  const rest = items.length - shown.length;
  const joined = shown.length > 1 ? `${shown.slice(0, -1).join(', ')} and ${shown[shown.length - 1]}` : shown[0] ?? '';
  return rest > 0 ? `${joined}, and ${rest} more` : joined;
};

export function buildPatientNarrative({ patient, medications, diagnoses, tasks, recalls, appointments }: NarrativeInput): PatientNarrative {
  const today = dayjs().startOf('day');
  const activeMeds = medications.filter((m) => m.status === 'Active');
  const activeDx = diagnoses.filter((d) => d.status === 'Active' || d.status === 'Chronic');
  const openTasks = tasks.filter((t) => t.status === 'Open' || t.status === 'In Progress');
  const overdueTasks = openTasks.filter((t) => dayjs(t.dueDate).isBefore(today));
  const dueRecalls = recalls.filter((r) => r.status === 'Due');
  const upcoming = appointments
    .filter((a) => !dayjs(a.date).isBefore(today) && !['Cancelled', 'No Show', 'Completed'].includes(a.status))
    .sort((a, b) => `${a.date} ${a.startTime}`.localeCompare(`${b.date} ${b.startTime}`));
  const lastVisit = appointments.filter((a) => a.status === 'Completed').sort((a, b) => b.date.localeCompare(a.date))[0];

  const demographics = `${patient.fullName}, ${patient.age} years old, ${patient.gender.toLowerCase()}, MRN ${patient.mrn}. Primary provider ${patient.primaryProviderName}.`;

  const diagnosisText = activeDx.length
    ? `Active problem list: ${list(activeDx.map((d) => d.description))}.`
    : diagnoses.length
      ? `No active diagnoses; ${diagnoses.length} resolved or inactive on record.`
      : 'No diagnoses recorded.';

  const medicationText = activeMeds.length
    ? `Currently on ${activeMeds.length} medication${activeMeds.length === 1 ? '' : 's'}: ${list(activeMeds.map((m) => `${m.name}${m.dosage ? ` ${m.dosage}` : ''}${m.frequency ? ` ${m.frequency.toLowerCase()}` : ''}`))}.`
    : medications.length
      ? `No active medications; ${medications.length} in the history.`
      : 'No medications recorded.';

  const taskText = openTasks.length
    ? `${openTasks.length} open task${openTasks.length === 1 ? '' : 's'}${overdueTasks.length ? `, ${overdueTasks.length} overdue` : ''}: ${list(openTasks.map((t) => t.title))}.`
    : 'No open tasks.';

  const recallText = dueRecalls.length
    ? `${dueRecalls.length} recall${dueRecalls.length === 1 ? '' : 's'} due: ${list(dueRecalls.map((r) => `${r.reason} on ${dayjs(r.dueDate).format('D MMM YYYY')}`))}.`
    : recalls.length
      ? 'No recalls are due.'
      : 'No recalls set.';

  const appointmentText = upcoming.length
    ? `Next appointment: ${upcoming[0].type} with ${upcoming[0].providerName} on ${dayjs(upcoming[0].date).format('D MMM YYYY')} at ${dayjs(`2000-01-01T${upcoming[0].startTime}`).format('h:mm A')}${upcoming.length > 1 ? `, plus ${upcoming.length - 1} more booked` : ''}.`
    : lastVisit
      ? `No upcoming appointment. Last completed visit was on ${dayjs(lastVisit.date).format('D MMM YYYY')}.`
      : 'No appointments recorded.';

  const sections = [
    { title: 'Patient', body: demographics },
    { title: 'Diagnoses', body: diagnosisText },
    { title: 'Medications', body: medicationText },
    { title: 'Tasks', body: taskText },
    { title: 'Recalls', body: recallText },
    { title: 'Appointments', body: appointmentText },
  ];

  return { text: sections.map((s) => s.body).join(' '), sections };
}
